---
# tasks file for ansible-role-nhc
#
- name: template in nhc.conf
  ansible.builtin.template:
    src: nhc.conf.j2
    dest: /etc/nhc/nhc.conf
    mode: '0644'
    backup: yes

- name: template in extra nhc scripts
  ansible.builtin.template:
    src: {{ item }}
    dest: /etc/nhc/scripts/{{ item }}
    mode:  '0644'
    backup: yes
  with_items: "{{ nhc_scripts }}"
  when: nhc_scripts.0 != ""
