---
# tasks file for ansible-role-nhc
#
#
- name: install NHC from url
  ansible.builtin.package:
    name: {{ nhc_url }}
    state: {{'latest' if nhc_upgarde else 'present'}}

- name: install NHC from a yum repo
  ansible.builtin.package:
    name: lbnl-nhc
  when: nhc_github == False 
