---
# tasks file for ansible-role-nhc
#
- name: Get nhc version
  ansible.builtin.package_facts:
    manager: auto

- name: install nhc
  ansible.builtin.include_tasks: install.yml
  when: nhc_version not in ansible_facts.packages['nhc']|map(attribute='version')

- name: configure nhc 
  ansible.builtin.import_tasks: configure.yml
